/**
 * packages/world — map/terrain provider abstraction (REQUIREMENT 012, 019).
 *
 * The scene core never knows which provider it is talking to. Every external
 * basemap / DEM / geocoder source sits behind one of these interfaces, so the
 * app works with zero providers configured (REQUIREMENT 119) and can add
 * OpenStreetMap, MapLibre DEM, Terrarium or a user's own tile server without
 * touching the renderer.
 *
 * Every method takes an AbortSignal. Stale requests must be discardable
 * (REQUIREMENT: every async job is cancellable).
 */

export interface TileDescriptor {
  z: number;
  x: number;
  y: number;
}

export interface ProviderInfo {
  id: string;
  name: string;
  kind: 'raster-imagery' | 'vector' | 'terrain-dem' | 'geocoder';
  attribution: string;
  license: string;
  minZoom: number;
  maxZoom: number;
  /** True when the provider needs no network access at all. */
  offline: boolean;
  /** True when a key/URL must be supplied by the user before use. */
  requiresConfiguration: boolean;
}

export interface RasterTileResult {
  data: Float32Array | Uint8ClampedArray;
  width: number;
  height: number;
  /** Elevation encoding, when the tile is a DEM. */
  encoding?: 'mapbox' | 'terrarium' | 'gray16' | 'rgba';
  bytes: number;
}

export interface ImageryProvider {
  info: ProviderInfo;
  fetchTile(t: TileDescriptor, signal: AbortSignal): Promise<{ blob: Blob; bytes: number }>;
}

export interface TerrainProvider {
  info: ProviderInfo;
  fetchDem(t: TileDescriptor, signal: AbortSignal): Promise<RasterTileResult>;
}

export interface GeocodeResult {
  name: string;
  lat: number;
  lon: number;
  /** Suggested camera distance in metres for the result's extent. */
  suggestedDistance: number;
  source: string;
}

export interface GeocoderProvider {
  info: ProviderInfo;
  search(query: string, signal: AbortSignal): Promise<GeocodeResult[]>;
}

/* ------------------------------------------------------------- registry --- */

export class ProviderRegistry {
  private providers = new Map<string, ProviderInfo & { instance: unknown }>();

  register(p: ProviderInfo, instance: unknown): void {
    this.providers.set(p.id, { ...p, instance });
  }

  get<T>(id: string): T | null {
    const p = this.providers.get(id);
    return p ? (p.instance as T) : null;
  }

  info(id: string): ProviderInfo | null {
    const p = this.providers.get(id);
    if (!p) return null;
    const { instance: _instance, ...info } = p;
    void _instance;
    return info as ProviderInfo;
  }

  list(kind?: ProviderInfo['kind']): ProviderInfo[] {
    return [...this.providers.values()]
      .filter((p) => !kind || p.kind === kind)
      .map(({ instance: _i, ...rest }) => {
        void _i;
        return rest as ProviderInfo;
      });
  }

  unregister(id: string): void {
    this.providers.delete(id);
  }
}

/* --------------------------------------------------------------- offline --- */

/**
 * A fully offline, procedural imagery provider used for the demo worlds and as
 * the default when the user has configured nothing. It generates a plausible
 * map-like tile on a canvas — clearly labelled as synthetic (REQUIREMENT 138,
 * 119). No network, no attribution debt.
 */
export class SyntheticImageryProvider implements ImageryProvider {
  readonly info: ProviderInfo = {
    id: 'synthetic',
    name: 'Synthetic (offline)',
    kind: 'raster-imagery',
    attribution: 'Procedurally generated by 3DMapMaker Next. Not real map data.',
    license: 'CC0 (generated at runtime)',
    minZoom: 0,
    maxZoom: 18,
    offline: true,
    requiresConfiguration: false,
  };
  private readonly size: number;

  constructor(size = 256) {
    this.size = size;
  }

  async fetchTile(t: TileDescriptor, signal: AbortSignal): Promise<{ blob: Blob; bytes: number }> {
    if (signal.aborted) throw new DOMException('aborted', 'AbortError');
    const canvas = document.createElement('canvas');
    canvas.width = this.size;
    canvas.height = this.size;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Canvas 2D unavailable');
    const seed = (t.z * 73856093) ^ (t.x * 19349663) ^ (t.y * 83492791);
    let s = seed >>> 0;
    const rnd = () => {
      s = (s * 1664525 + 1013904223) >>> 0;
      return s / 4294967296;
    };
    ctx.fillStyle = '#20303a';
    ctx.fillRect(0, 0, this.size, this.size);
    // landmasses
    for (let i = 0; i < 14; i++) {
      const x = rnd() * this.size;
      const y = rnd() * this.size;
      const r = 12 + rnd() * 60;
      const g = ctx.createRadialGradient(x, y, 0, x, y, r);
      g.addColorStop(0, 'rgba(58,86,66,0.85)');
      g.addColorStop(1, 'rgba(58,86,66,0)');
      ctx.fillStyle = g;
      ctx.beginPath();
      ctx.arc(x, y, r, 0, Math.PI * 2);
      ctx.fill();
    }
    // road grid
    ctx.strokeStyle = 'rgba(190,190,180,0.22)';
    ctx.lineWidth = 1;
    const cells = 4 + Math.floor(rnd() * 4);
    for (let i = 0; i <= cells; i++) {
      const p = (i / cells) * this.size;
      ctx.beginPath();
      ctx.moveTo(p, 0);
      ctx.lineTo(p, this.size);
      ctx.moveTo(0, p);
      ctx.lineTo(this.size, p);
      ctx.stroke();
    }
    if (signal.aborted) throw new DOMException('aborted', 'AbortError');
    const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
    if (!blob) throw new Error('Tile encoding failed');
    return { blob, bytes: blob.size };
  }
}

/**
 * Terrain-RGB DEM provider template. It is registered only when the user
 * supplies a URL template, so nothing is hard-coded to a commercial source
 * (REQUIREMENT 012, 119).
 */
export class UrlTemplateTerrainProvider implements TerrainProvider {
  readonly info: ProviderInfo;
  private readonly urlTemplate: string;
  private readonly encoding: 'mapbox' | 'terrarium';

  constructor(opts: {
    id: string;
    name: string;
    urlTemplate: string;
    encoding?: 'mapbox' | 'terrarium';
    attribution: string;
    license: string;
    maxZoom?: number;
  }) {
    this.urlTemplate = opts.urlTemplate;
    this.encoding = opts.encoding ?? 'mapbox';
    this.info = {
      id: opts.id,
      name: opts.name,
      kind: 'terrain-dem',
      attribution: opts.attribution,
      license: opts.license,
      minZoom: 0,
      maxZoom: opts.maxZoom ?? 14,
      offline: false,
      requiresConfiguration: true,
    };
  }

  /** Reject anything that is not http(s) to a host the user configured. */
  static validateTemplate(template: string): { ok: boolean; error?: string } {
    if (!template.includes('{z}') || !template.includes('{x}') || !template.includes('{y}')) {
      return { ok: false, error: 'URL template must contain {z}, {x} and {y} placeholders.' };
    }
    try {
      const url = new URL(template.replace('{z}', '0').replace('{x}', '0').replace('{y}', '0'));
      if (url.protocol !== 'https:' && url.protocol !== 'http:') {
        return { ok: false, error: 'Only http(s) tile URLs are allowed.' };
      }
      return { ok: true };
    } catch {
      return { ok: false, error: 'That is not a valid URL.' };
    }
  }

  async fetchDem(t: TileDescriptor, signal: AbortSignal): Promise<RasterTileResult> {
    const check = UrlTemplateTerrainProvider.validateTemplate(this.urlTemplate);
    if (!check.ok) throw new Error(check.error);
    const url = this.urlTemplate.replace('{z}', String(t.z)).replace('{x}', String(t.x)).replace('{y}', String(t.y));
    const res = await fetch(url, { signal, mode: 'cors' });
    if (!res.ok) throw new Error(`DEM tile ${t.z}/${t.x}/${t.y} failed: HTTP ${res.status}`);
    const blob = await res.blob();
    const bitmap = await createImageBitmap(blob);
    const canvas = document.createElement('canvas');
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Canvas 2D unavailable');
    ctx.drawImage(bitmap, 0, 0);
    const img = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
    bitmap.close();
    const { decodeTerrainRgb } = await import('@3dmm/terrain');
    const data = decodeTerrainRgb(img.data, img.width, img.height, this.encoding);
    return { data, width: img.width, height: img.height, encoding: this.encoding, bytes: data.byteLength };
  }
}

/**
 * Offline geocoder. Matches against the user's own bookmarks, panorama node
 * names and authored markers, so search works with no network and no API key
 * (REQUIREMENT 080, 118, 119).
 */
export class LocalGeocoder implements GeocoderProvider {
  readonly info: ProviderInfo = {
    id: 'local',
    name: 'This project',
    kind: 'geocoder',
    attribution: 'Searches bookmarks, panoramas and markers in the open project.',
    license: 'n/a',
    minZoom: 0,
    maxZoom: 24,
    offline: true,
    requiresConfiguration: false,
  };

  constructor(private entries: Array<{ name: string; lat: number; lon: number; distance?: number }>) {}

  setEntries(entries: Array<{ name: string; lat: number; lon: number; distance?: number }>): void {
    this.entries = entries;
  }

  async search(query: string, signal: AbortSignal): Promise<GeocodeResult[]> {
    if (signal.aborted) throw new DOMException('aborted', 'AbortError');
    const q = query.trim().toLowerCase();
    if (!q) return [];
    return this.entries
      .filter((e) => e.name.toLowerCase().includes(q))
      .slice(0, 20)
      .map((e) => ({
        name: e.name,
        lat: e.lat,
        lon: e.lon,
        suggestedDistance: e.distance ?? 250,
        source: 'project',
      }));
  }
}

/** Parse "lat, lon" / "lat lon" free-text coordinates as a last-resort search. */
export function parseCoordinateQuery(query: string): GeocodeResult | null {
  const m = /^\s*(-?\d+(?:\.\d+)?)\s*[, ]\s*(-?\d+(?:\.\d+)?)\s*$/.exec(query);
  if (!m) return null;
  const lat = Number(m[1]);
  const lon = Number(m[2]);
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null;
  if (lat < -90 || lat > 90 || lon < -180 || lon > 180) return null;
  return { name: `${lat.toFixed(5)}, ${lon.toFixed(5)}`, lat, lon, suggestedDistance: 400, source: 'coordinates' };
}
