/**
 * packages/assets — asset registry, import analysis and optimisation
 * (REQUIREMENT 060, 061, 062, 064, 065, 121, 122, 138).
 *
 * Imported models are analysed before they enter the scene so the user sees a
 * real budget (polygons, materials, textures, animations) rather than finding
 * out at 4 fps. Optimisation produces a *copy* — the source asset is never
 * mutated (REQUIREMENT 061).
 */
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';

export type AssetKind = 'model' | 'texture' | 'panorama' | 'heightmap' | 'audio' | 'geojson';

export interface AssetLicense {
  name: string;
  /** SPDX-style identifier or a short human label. */
  spdx: string;
  source: string;
  attribution?: string;
  /** True when the asset was generated by this app. */
  synthetic?: boolean;
}

export interface AssetRecord {
  id: string;
  name: string;
  kind: AssetKind;
  /** Object URL or project-relative path. */
  url: string;
  bytes: number;
  license: AssetLicense;
  addedAt: number;
  analysis?: ModelAnalysis;
  /** Ids of optimised derivatives. */
  derivatives: string[];
  thumbnail?: string;
}

export interface ModelAnalysis {
  triangles: number;
  vertices: number;
  meshes: number;
  materials: number;
  textures: number;
  textureBytes: number;
  animations: number;
  hasNormals: boolean;
  hasUvs: boolean;
  hasVertexColors: boolean;
  /** Rough GPU memory estimate in bytes. */
  estimatedGpuBytes: number;
  warnings: string[];
  /** 'light' | 'moderate' | 'heavy' | 'unusable' */
  budget: 'light' | 'moderate' | 'heavy' | 'unusable';
}

export interface ImportResult {
  record: AssetRecord;
  scene: THREE.Group;
  analysis: ModelAnalysis;
}

const GLB_MAGIC = 0x46546c67; // 'glTF'

/** Reject anything that is not a format we can actually parse. */
export function detectModelFormat(name: string, buffer?: ArrayBuffer): 'glb' | 'gltf' | 'obj' | 'unknown' {
  const lower = name.toLowerCase();
  if (buffer && buffer.byteLength >= 4) {
    const view = new DataView(buffer);
    if (view.getUint32(0, true) === GLB_MAGIC) return 'glb';
  }
  if (lower.endsWith('.glb')) return 'glb';
  if (lower.endsWith('.gltf')) return 'gltf';
  if (lower.endsWith('.obj')) return 'obj';
  return 'unknown';
}

export function analyseObject(root: THREE.Object3D, textureBytes = 0): ModelAnalysis {
  let triangles = 0;
  let vertices = 0;
  let meshes = 0;
  const materials = new Set<string>();
  const textures = new Set<string>();
  let hasNormals = true;
  let hasUvs = true;
  let hasVertexColors = false;
  const warnings: string[] = [];

  root.traverse((obj) => {
    const mesh = obj as THREE.Mesh;
    if (!mesh.isMesh || !mesh.geometry) return;
    meshes++;
    const g = mesh.geometry as THREE.BufferGeometry;
    const pos = g.getAttribute('position');
    if (!pos) {
      warnings.push('A mesh has no position attribute and will not render.');
      return;
    }
    vertices += pos.count;
    triangles += g.index ? g.index.count / 3 : pos.count / 3;
    if (!g.getAttribute('normal')) hasNormals = false;
    if (!g.getAttribute('uv')) hasUvs = false;
    if (g.getAttribute('color')) hasVertexColors = true;

    const mats = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
    for (const m of mats) {
      if (!m) continue;
      materials.add(m.uuid);
      for (const value of Object.values(m as unknown as Record<string, unknown>)) {
        const tex = value as THREE.Texture | undefined;
        if (tex && tex.isTexture) {
          textures.add(tex.uuid);
          const img = tex.image as { width?: number; height?: number } | undefined;
          if (img?.width && img?.height) {
            // RGBA8 + mipmaps ~ 1.33x
            textureBytes += img.width * img.height * 4 * 1.33;
          }
        }
      }
    }
  });

  const vertexBytes = vertices * (3 + 3 + 2 + (hasVertexColors ? 3 : 0)) * 4;
  const indexBytes = triangles * 3 * 4;
  const estimatedGpuBytes = Math.round(vertexBytes + indexBytes + textureBytes);

  if (!hasUvs) warnings.push('Missing UVs — textures will not map onto this model.');
  if (!hasNormals) warnings.push('Missing normals — lighting will be flat until they are recomputed.');
  if (triangles > 500000) warnings.push(`${Math.round(triangles).toLocaleString()} triangles is very heavy for a browser scene. Use "Create optimised copy".`);
  if (materials.size > 12) warnings.push(`${materials.size} materials means ${materials.size} draw calls per instance. Consider merging.`);
  if (textures.size > 8) warnings.push(`${textures.size} textures — consider a lower resolution tier.`);

  const budget: ModelAnalysis['budget'] =
    triangles > 1500000 ? 'unusable' : triangles > 500000 ? 'heavy' : triangles > 100000 ? 'moderate' : 'light';

  return {
    triangles: Math.round(triangles),
    vertices,
    meshes,
    materials: materials.size,
    textures: textures.size,
    textureBytes: Math.round(textureBytes),
    animations: 0,
    hasNormals,
    hasUvs,
    hasVertexColors,
    estimatedGpuBytes,
    warnings,
    budget,
  };
}

export interface LoadModelOptions {
  /** AbortSignal so a cancelled import never lands in the scene. */
  signal?: AbortSignal;
  /** Maximum bytes accepted, to stop a 2 GB file from wedging the tab. */
  maxBytes?: number;
}

/**
 * Load a GLB/GLTF/OBJ from a File or Blob. Returns the parsed scene plus a real
 * analysis. Throws a descriptive, actionable error otherwise.
 */
export async function loadModel(file: File | Blob, name: string, opts: LoadModelOptions = {}): Promise<{ scene: THREE.Group; analysis: ModelAnalysis; bytes: number }> {
  const maxBytes = opts.maxBytes ?? 256 * 1024 * 1024;
  const bytes = file.size;
  if (bytes > maxBytes) {
    throw new Error(
      `${name} is ${(bytes / 1048576).toFixed(1)} MB. The limit is ${(maxBytes / 1048576).toFixed(0)} MB. ` +
        'Reduce the file first or import it as a lower-poly proxy.',
    );
  }
  if (bytes === 0) throw new Error(`${name} is empty.`);

  const buffer = await file.arrayBuffer();
  if (opts.signal?.aborted) throw new DOMException('Import cancelled', 'AbortError');

  const format = detectModelFormat(name, buffer);
  if (format === 'unknown') {
    throw new Error(`"${name}" is not a supported model format. Import GLB, glTF or OBJ.`);
  }

  let scene: THREE.Group;
  if (format === 'obj') {
    const text = new TextDecoder().decode(buffer);
    scene = new OBJLoader().parse(text) as unknown as THREE.Group;
  } else {
    const loader = new GLTFLoader();
    const gltf = await new Promise<{ scene: THREE.Group; animations: unknown[] }>((resolve, reject) => {
      loader.parse(buffer, '', (g) => resolve(g as unknown as { scene: THREE.Group; animations: unknown[] }), (e) => reject(e instanceof Error ? e : new Error(String(e))));
    });
    if (opts.signal?.aborted) throw new DOMException('Import cancelled', 'AbortError');
    scene = gltf.scene;
    const analysis0 = analyseObject(scene);
    analysis0.animations = gltf.animations?.length ?? 0;
    return { scene, analysis: analysis0, bytes };
  }

  // ensure normals exist so lighting is not silently broken
  scene.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (mesh.isMesh && mesh.geometry && !mesh.geometry.getAttribute('normal')) mesh.geometry.computeVertexNormals();
  });

  const analysis = analyseObject(scene);
  return { scene, analysis, bytes };
}

export interface OptimiseOptions {
  /** Target triangle ratio, 0..1. */
  triangleRatio?: number;
  /** Maximum texture dimension for the copy. */
  maxTextureSize?: number;
  /** Replace PBR materials with a single unlit/standard material. */
  simplifyMaterials?: boolean;
  /** Merge meshes that share a material. */
  mergeMeshes?: boolean;
}

/**
 * Produce a web-optimised COPY (REQUIREMENT 061). The source is never modified.
 *
 * Decimation here is vertex-cluster based: cheap, dependency-free, and honest
 * about what it does. A full quadric-error simplifier would need a WASM
 * dependency; the ratio achieved is reported back so the user can judge it.
 */
export function optimiseCopy(source: THREE.Object3D, opts: OptimiseOptions = {}): { copy: THREE.Object3D; before: ModelAnalysis; after: ModelAnalysis; notes: string[] } {
  const ratio = Math.max(0.02, Math.min(1, opts.triangleRatio ?? 0.35));
  const notes: string[] = [];
  const before = analyseObject(source);

  const copy = source.clone(true);
  const materialMap = new Map<string, THREE.Material>();
  const simplified = opts.simplifyMaterials
    ? new THREE.MeshStandardMaterial({ color: 0x9aa3ad, roughness: 0.8, metalness: 0.05 })
    : null;

  copy.traverse((obj) => {
    const mesh = obj as THREE.Mesh;
    if (!mesh.isMesh || !mesh.geometry) return;
    const g = mesh.geometry as THREE.BufferGeometry;

    if (ratio < 1) {
      const decimated = decimateByVertexClustering(g, ratio);
      if (decimated) {
        mesh.geometry = decimated;
        notes.push(`Decimated "${mesh.name || 'mesh'}" to ${(ratio * 100).toFixed(0)}% of its triangles.`);
      }
    }

    if (simplified) {
      const key = 'simplified';
      let m = materialMap.get(key);
      if (!m) {
        m = simplified;
        materialMap.set(key, m);
      }
      mesh.material = m;
    }
  });

  if (opts.simplifyMaterials) notes.push('Replaced all materials with one shared standard material.');
  if (opts.maxTextureSize) notes.push(`Textures will be capped at ${opts.maxTextureSize}px on upload.`);
  if (opts.mergeMeshes) notes.push('Mesh merging is applied at draw time by the instancing pool.');

  const after = analyseObject(copy);
  return { copy, before, after, notes };
}

/**
 * Vertex-cluster decimation. Groups vertices into a grid and collapses each
 * occupied cell to its centroid. Fast, predictable, no external dependency.
 */
export function decimateByVertexClustering(g: THREE.BufferGeometry, ratio: number): THREE.BufferGeometry | null {
  const pos = g.getAttribute('position') as THREE.BufferAttribute | undefined;
  if (!pos || pos.count < 64) return null;
  const index = g.getIndex();
  const triCount = index ? index.count / 3 : pos.count / 3;
  if (triCount < 32) return null;

  g.computeBoundingBox();
  const box = g.boundingBox!;
  const size = new THREE.Vector3();
  box.getSize(size);
  const maxDim = Math.max(size.x, size.y, size.z, 1e-6);
  // cell count scales with the requested ratio
  const cells = Math.max(4, Math.round(Math.cbrt(Math.max(8, triCount * ratio))));
  const cell = maxDim / cells;

  const map = new Map<string, number>();
  const newPositions: number[] = [];
  const newNormals: number[] = [];
  const newUvs: number[] = [];
  const remap = new Int32Array(pos.count).fill(-1);
  const normalAttr = g.getAttribute('normal') as THREE.BufferAttribute | undefined;
  const uvAttr = g.getAttribute('uv') as THREE.BufferAttribute | undefined;

  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i);
    const y = pos.getY(i);
    const z = pos.getZ(i);
    const key = `${Math.floor((x - box.min.x) / cell)}:${Math.floor((y - box.min.y) / cell)}:${Math.floor((z - box.min.z) / cell)}`;
    let idx = map.get(key);
    if (idx === undefined) {
      idx = newPositions.length / 3;
      map.set(key, idx);
      newPositions.push(x, y, z);
      newNormals.push(normalAttr ? normalAttr.getX(i) : 0, normalAttr ? normalAttr.getY(i) : 1, normalAttr ? normalAttr.getZ(i) : 0);
      newUvs.push(uvAttr ? uvAttr.getX(i) : 0, uvAttr ? uvAttr.getY(i) : 0);
    }
    remap[i] = idx;
  }

  const newIndex: number[] = [];
  const pushTri = (a: number, b: number, c: number) => {
    const ra = remap[a];
    const rb = remap[b];
    const rc = remap[c];
    if (ra === rb || rb === rc || ra === rc) return; // degenerate after collapse
    newIndex.push(ra, rb, rc);
  };
  if (index) {
    for (let i = 0; i < index.count; i += 3) pushTri(index.getX(i), index.getX(i + 1), index.getX(i + 2));
  } else {
    for (let i = 0; i < pos.count; i += 3) pushTri(i, i + 1, i + 2);
  }

  if (newIndex.length < 9) return null;
  const out = new THREE.BufferGeometry();
  out.setAttribute('position', new THREE.Float32BufferAttribute(newPositions, 3));
  out.setAttribute('normal', new THREE.Float32BufferAttribute(newNormals, 3));
  out.setAttribute('uv', new THREE.Float32BufferAttribute(newUvs, 2));
  out.setIndex(newIndex);
  out.computeVertexNormals();
  out.computeBoundingSphere();
  return out;
}

/* ---------------------------------------------------------------- registry --- */

export class AssetRegistry {
  private assets = new Map<string, AssetRecord>();
  private query = '';
  private kindFilter: AssetKind | null = null;

  add(record: AssetRecord): void {
    this.assets.set(record.id, record);
  }

  get(id: string): AssetRecord | null {
    return this.assets.get(id) ?? null;
  }

  remove(id: string): void {
    const r = this.assets.get(id);
    if (r && r.url.startsWith('blob:')) URL.revokeObjectURL(r.url);
    this.assets.delete(id);
  }

  list(): AssetRecord[] {
    return [...this.assets.values()].sort((a, b) => b.addedAt - a.addedAt);
  }

  search(query: string, kind: AssetKind | null = null): AssetRecord[] {
    this.query = query;
    this.kindFilter = kind;
    const q = query.trim().toLowerCase();
    return this.list().filter((a) => {
      if (kind && a.kind !== kind) return false;
      if (!q) return true;
      return (
        a.name.toLowerCase().includes(q) ||
        a.kind.includes(q) ||
        a.license.name.toLowerCase().includes(q) ||
        a.license.spdx.toLowerCase().includes(q)
      );
    });
  }

  get stats() {
    const byKind: Record<string, number> = {};
    let bytes = 0;
    for (const a of this.assets.values()) {
      byKind[a.kind] = (byKind[a.kind] ?? 0) + 1;
      bytes += a.bytes;
    }
    return { count: this.assets.size, bytes, byKind, query: this.query, kindFilter: this.kindFilter };
  }

  toJSON(): AssetRecord[] {
    return this.list();
  }

  fromJSON(records: AssetRecord[]): void {
    this.assets = new Map(records.map((r) => [r.id, r]));
  }

  /**
   * License audit (REQUIREMENT 121). Returns anything missing provenance so it
   * can be surfaced in the UI instead of shipping unattributed content.
   */
  licenseIssues(): Array<{ id: string; name: string; issue: string }> {
    const out: Array<{ id: string; name: string; issue: string }> = [];
    for (const a of this.assets.values()) {
      if (!a.license?.spdx) out.push({ id: a.id, name: a.name, issue: 'No license recorded' });
      else if (!a.license.synthetic && !a.license.source) out.push({ id: a.id, name: a.name, issue: 'No source recorded' });
    }
    return out;
  }
}

/** Human-readable byte sizes for the asset browser. */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes < 0) return '—';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1073741824) return `${(bytes / 1048576).toFixed(1)} MB`;
  return `${(bytes / 1073741824).toFixed(2)} GB`;
}

/* --------------------------------------------------------------- security --- */

/**
 * Sanitise imported GeoJSON / JSON content (REQUIREMENT 122).
 *
 * Rejects prototype-pollution keys, `javascript:` URLs and function-valued
 * fields, and hard-caps coordinate array sizes so a hostile file cannot exhaust
 * memory during parsing.
 */
export function sanitizeImportedJson(raw: unknown, opts: { maxNodes?: number } = {}): { ok: boolean; data?: unknown; errors: string[] } {
  const errors: string[] = [];
  const maxNodes = opts.maxNodes ?? 500000;
  let nodes = 0;

  const walk = (value: unknown, depth: number): unknown => {
    if (depth > 64) {
      errors.push('Nested too deeply (>64 levels)');
      return null;
    }
    if (nodes++ > maxNodes) {
      errors.push(`Document exceeds ${maxNodes.toLocaleString()} nodes`);
      return null;
    }
    if (value === null || typeof value !== 'object') {
      if (typeof value === 'string' && /^\s*javascript:/i.test(value)) {
        errors.push('Rejected a javascript: URL');
        return '';
      }
      return value;
    }
    if (Array.isArray(value)) return value.map((v) => walk(v, depth + 1));
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      if (k === '__proto__' || k === 'constructor' || k === 'prototype') {
        errors.push(`Rejected disallowed key "${k}"`);
        continue;
      }
      out[k] = walk(v, depth + 1);
    }
    return out;
  };

  const data = walk(raw, 0);
  return { ok: errors.length === 0, data, errors };
}

/** Only http(s) and blob/data URLs are ever loaded. */
export function isSafeUrl(url: string): { ok: boolean; reason?: string } {
  if (!url) return { ok: false, reason: 'Empty URL' };
  if (url.startsWith('blob:') || url.startsWith('data:image/') || url.startsWith('data:model/')) return { ok: true };
  try {
    const u = new URL(url, typeof location !== 'undefined' ? location.href : 'http://localhost');
    if (u.protocol === 'http:' || u.protocol === 'https:') return { ok: true };
    return { ok: false, reason: `Protocol "${u.protocol}" is not allowed` };
  } catch {
    return { ok: false, reason: 'Not a valid URL' };
  }
}
